import { createRequire } from "node:module";
import { describe, expect, it } from "vitest";

const require = createRequire(import.meta.url);
const { applyThothAndroidReleaseSigning } =
  require("../../plugins/with-thoth-android-release-signing.cjs") as {
    applyThothAndroidReleaseSigning(contents: string): string;
  };

describe("Thoth Android release signing config plugin", () => {
  it("adds one strict release signing block and remains idempotent", () => {
    const source = "android {\n  buildTypes {\n    release {}\n  }\n}\n";
    const once = applyThothAndroidReleaseSigning(source);
    const twice = applyThothAndroidReleaseSigning(once);

    expect(twice).toBe(once);
    expect(once.match(/@generated by with-thoth-android-release-signing/g)).toHaveLength(1);
    expect(once).toContain("THOTH_ANDROID_KEYSTORE_PATH");
    expect(once).toContain("throw new GradleException");
    expect(once).toContain("signingConfig signingConfigs.thothRelease");
  });
});
